rm(list=ls())
library(readxl)
library(tibble)
library(dunn.test)
y=read_excel("C:/Users/there/Desktop/survey/data/arm2deg.xlsx",sheet="Sheet1",range="B1:J52",col_names=TRUE,col_types="guess",na="")
y1=y[[1]]
y2=y[[2]]
y3=y[[3]]
y4=y[[4]]
y5=y[[5]]
y6=y[[6]]
y7=y[[7]]
y8=y[[8]]
y9=y[[9]]
yy=c(y1,y2,y3,y4,y5,y6,y7,y8,y9)
kk=length(y1)
n=rep(kk,9)
gp=rep(1:9,n)
dat=data.frame(yy,gp)
dat$gp<-factor(dat$gp,labels=c("목표/기대수준","학습동기","참여도","유용성","이해도","집중도","효과성","만족도","교수"))
md=lm(dat$yy~dat$gp,data=dat)
shapiro.test(resid(md))
out=kruskal.test(dat$yy~dat$gp,data=dat)
rt=dunn.test(dat$yy,dat$gp,method='bonferroni')
summary(rt)
par(las=1)
par(mar=c(5,12,4,2))
plot(rt)